# Generated by Django 5.1.6 on 2026-04-21 15:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0116_alter_employee_adminpayfund'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('health_type', models.CharField(blank=True, max_length=50)),
                ('health_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dental_type', models.CharField(blank=True, max_length=50)),
                ('dental_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('life_type', models.CharField(blank=True, max_length=50)),
                ('life_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Insurance Assignment',
                'verbose_name_plural': 'Insurance Assignments',
                'db_table': 'Insurance Rate',
                'ordering': ['year', 'person'],
            },
        ),
        migrations.CreateModel(
            name='InsurancePercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('percent_of_time', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Insurance Percentage',
                'verbose_name_plural': 'Insurance Percentages',
                'db_table': 'Insurance Percentage',
                'ordering': ['start_date', 'end_date', 'person', 'fund'],
            },
        ),
        migrations.RemoveField(
            model_name='grantitem',
            name='line',
        ),
        migrations.DeleteModel(
            name='Variable',
        ),
        migrations.AlterModelOptions(
            name='accesscontrol',
            options={'permissions': [('has_full_access', 'Has full access to all views')], 'verbose_name': 'Access Control'},
        ),
        migrations.AlterModelOptions(
            name='activitylist',
            options={'ordering': ['ActivityList_id'], 'verbose_name': 'Activity List'},
        ),
        migrations.AlterModelOptions(
            name='benefits',
            options={'ordering': ['employee'], 'verbose_name': 'Benefits'},
        ),
        migrations.AlterModelOptions(
            name='budgetactions',
            options={'ordering': ['ba_id'], 'verbose_name': 'Budget Actions'},
        ),
        migrations.AlterModelOptions(
            name='carryover',
            options={'ordering': ['dept'], 'verbose_name': 'Carryover'},
        ),
        migrations.AlterModelOptions(
            name='dept',
            options={'ordering': ['dept_name'], 'verbose_name': 'Dept'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['surname', 'first_name'], 'verbose_name': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['date'], 'verbose_name': 'Expense'},
        ),
        migrations.AlterModelOptions(
            name='fund',
            options={'ordering': ['fund_id', 'fund_name'], 'verbose_name': 'Fund'},
        ),
        migrations.AlterModelOptions(
            name='grant',
            options={'ordering': ['grant_name'], 'verbose_name': 'Grant'},
        ),
        migrations.AlterModelOptions(
            name='grantline',
            options={'ordering': ['grant'], 'verbose_name': 'Grant Line'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['item_name'], 'verbose_name': 'Item'},
        ),
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ['line_name'], 'verbose_name': 'Line'},
        ),
        migrations.AlterModelOptions(
            name='payperiod',
            options={'ordering': ['periodStart'], 'verbose_name': 'Pay Period'},
        ),
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['beg_date'], 'verbose_name': 'Payroll'},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['name'], 'verbose_name': 'People'},
        ),
        migrations.AlterModelOptions(
            name='revenue',
            options={'ordering': ['date'], 'verbose_name': 'Revenue'},
        ),
        migrations.AlterModelOptions(
            name='testing',
            options={'ordering': ['testing_name']},
        ),
        migrations.RemoveField(
            model_name='activitylist',
            name='odhafr',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='odhafr',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='fund_budgeted',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='mac_elig',
        ),
        migrations.RemoveField(
            model_name='grant',
            name='received',
        ),
        migrations.RemoveField(
            model_name='grantline',
            name='cofund',
        ),
        migrations.RemoveField(
            model_name='grantline',
            name='county_code',
        ),
        migrations.RemoveField(
            model_name='grantline',
            name='gen_ledger',
        ),
        migrations.RemoveField(
            model_name='grantline',
            name='line_budget_remaining',
        ),
        migrations.RemoveField(
            model_name='grantline',
            name='line_budget_spent',
        ),
        migrations.RemoveField(
            model_name='grantline',
            name='line_total_income',
        ),
        migrations.RemoveField(
            model_name='line',
            name='line_budget_remaining',
        ),
        migrations.RemoveField(
            model_name='line',
            name='line_budget_spent',
        ),
        migrations.RemoveField(
            model_name='line',
            name='line_total_income',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='confirmation',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='odhafr',
        ),
        migrations.AddField(
            model_name='activitylist',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='WCHDApp.item', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='activitylist',
            name='payType',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('admin', 'Admin'), ('special', 'Special')], max_length=10, null=True, verbose_name='Pay Type'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='employee',
            name='payItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pay_item', to='WCHDApp.item', verbose_name='Pay Item'),
        ),
        migrations.AddField(
            model_name='employee',
            name='specialPayItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='special_pay_item', to='WCHDApp.item', verbose_name='Special Pay Item'),
        ),
        migrations.AddField(
            model_name='expense',
            name='expenseFullID',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Expense Full ID'),
        ),
        migrations.AddField(
            model_name='fund',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year'),
        ),
        migrations.AddField(
            model_name='grant',
            name='maxRevenueLines',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='revenue',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='DoB'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ssn',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='SSN'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='fund_id',
            field=models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Fund ID'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='fund_total',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Revenue'),
        ),
        migrations.AlterField(
            model_name='people',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='people',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='people',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='people',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='people',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip Code'),
        ),
        migrations.AlterModelTable(
            name='accesscontrol',
            table='Access Control',
        ),
        migrations.AddField(
            model_name='insuranceassignment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.people'),
        ),
        migrations.AddField(
            model_name='insurancepercentage',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.fund'),
        ),
        migrations.AddField(
            model_name='insurancepercentage',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.people'),
        ),
        migrations.DeleteModel(
            name='GrantItem',
        ),
        migrations.AlterUniqueTogether(
            name='insuranceassignment',
            unique_together={('person', 'year')},
        ),
    ]
