# Generated by Django 5.1.6 on 2026-04-28 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0117_insuranceassignment_insurancepercentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('percent_of_time', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('dental', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('health', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.fund')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.people')),
            ],
            options={
                'verbose_name': 'Insurance Allocation',
                'verbose_name_plural': 'Insurance Allocations',
                'constraints': [models.UniqueConstraint(fields=('year', 'month', 'person', 'fund'), name='unique_insurance_allocation')],
            },
        ),
    ]
