# Generated by Django 5.1.6 on 2026-04-28 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0118_insuranceallocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insuranceallocation',
            old_name='person',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='insurancepercentage',
            old_name='person',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='insuranceassignment',
            old_name='person',
            new_name='employee',
        ),
        migrations.AlterModelOptions(
            name='insuranceallocation',
            options={'ordering': ['year', 'month', 'employee', 'fund'], 'verbose_name': 'Insurance Allocation', 'verbose_name_plural': 'Insurance Allocations'},
        ),
        migrations.AlterModelOptions(
            name='insuranceassignment',
            options={'ordering': ['year', 'employee'], 'verbose_name': 'Insurance Assignment', 'verbose_name_plural': 'Insurance Assignments'},
        ),
        migrations.AlterModelOptions(
            name='insurancepercentage',
            options={'ordering': ['start_date', 'end_date', 'employee', 'fund'], 'verbose_name': 'Insurance Percentage', 'verbose_name_plural': 'Insurance Percentages'},
        ),
        migrations.RemoveConstraint(
            model_name='insuranceallocation',
            name='unique_insurance_allocation',
        ),
        migrations.AlterUniqueTogether(
            name='insuranceassignment',
            unique_together={('employee', 'year')},
        ),
        migrations.AddField(
            model_name='insurancepercentage',
            name='activityList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WCHDApp.activitylist', verbose_name='Activity List'),
        ),
        migrations.AlterField(
            model_name='insuranceallocation',
            name='dental',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Dental'),
        ),
        migrations.AlterField(
            model_name='insuranceallocation',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.fund', verbose_name='Fund'),
        ),
        migrations.AlterField(
            model_name='insuranceallocation',
            name='health',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Health'),
        ),
        migrations.AlterField(
            model_name='insuranceallocation',
            name='month',
            field=models.IntegerField(verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='insuranceallocation',
            name='percent_of_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Percent Of Time'),
        ),
        migrations.AlterField(
            model_name='insuranceallocation',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
        migrations.AlterModelTable(
            name='insuranceallocation',
            table='Insurance Allocation',
        ),
    ]
