# Generated by Django 5.1.6 on 2026-04-28 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0119_alter_insuranceallocation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceallocation',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='insuranceassignment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.employee'),
        ),
        migrations.AlterField(
            model_name='insurancepercentage',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.employee'),
        ),
    ]
