# Generated by Django 5.1.6 on 2026-04-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0121_insuranceallocation_life'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceallocation',
            name='life',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Life'),
        ),
    ]
