# Generated by Django 5.1.6 on 2026-04-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0122_alter_insuranceallocation_life'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceallocation',
            name='life',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Life'),
        ),
        migrations.AlterUniqueTogether(
            name='insuranceallocation',
            unique_together={('year', 'month', 'employee', 'fund')},
        ),
    ]
