# Generated by Django 5.1.6 on 2026-04-30 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0123_alter_insuranceallocation_life_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='fund_total',
        ),
    ]
