# Generated by Django 5.1.6 on 2026-04-30 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0124_remove_fund_fund_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='sof',
        ),
    ]
