# Generated by Django 5.1.6 on 2026-04-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0125_remove_fund_sof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='fund_type',
            field=models.CharField(blank=True, choices=[('FEDERAL', 'Federal'), ('STATE', 'State'), ('LOCAL', 'Local')], max_length=50, null=True, verbose_name='Fund Type'),
        ),
    ]
