# Generated by Django 5.1.6 on 2026-04-30 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0126_alter_item_fund_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancepercentage',
            name='activityList',
        ),
    ]
