# Generated by Django 5.1.6 on 2026-05-03 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0127_remove_insurancepercentage_activitylist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Benefits',
        ),
    ]
