# Generated by Django 5.1.6 on 2026-05-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0128_delete_benefits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylist',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['ActivityList_id'], 'permissions': [('manage_activity_lists', 'Can manage activity lists'), ('view_activity_reports', 'Can view activity reports')], 'verbose_name': 'Activity List'},
        ),
        migrations.AlterModelOptions(
            name='budgetactions',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['ba_id'], 'permissions': [('approve_budget_actions', 'Can approve budget actions'), ('manage_budget_actions', 'Can manage budget actions')], 'verbose_name': 'Budget Actions'},
        ),
        migrations.AlterModelOptions(
            name='carryover',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['dept'], 'permissions': [('manage_carryover', 'Can manage carryover'), ('view_carryover_reports', 'Can view carryover reports')], 'verbose_name': 'Carryover'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['surname', 'first_name'], 'permissions': [('manage_employees', 'Can manage employees'), ('view_employee_sensitive_data', 'Can view employee sensitive data'), ('manage_employee_pay', 'Can manage employee pay')], 'verbose_name': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['date'], 'permissions': [('manage_expenses', 'Can manage expenses'), ('approve_expenses', 'Can approve expenses'), ('view_expense_reports', 'Can view expense reports')], 'verbose_name': 'Expense'},
        ),
        migrations.AlterModelOptions(
            name='fund',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['fund_id', 'fund_name'], 'permissions': [('approve_fund', 'Can approve fund'), ('lock_fund', 'Can lock fund'), ('edit_fund_budget', 'Can edit fund budget'), ('view_fund_reports', 'Can view fund reports')], 'verbose_name': 'Fund'},
        ),
        migrations.AlterModelOptions(
            name='grant',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['grant_name'], 'permissions': [('manage_grants', 'Can manage grants'), ('approve_grants', 'Can approve grants'), ('view_grant_reports', 'Can view grant reports')], 'verbose_name': 'Grant'},
        ),
        migrations.AlterModelOptions(
            name='grantline',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['grant'], 'permissions': [('manage_grant_lines', 'Can manage grant lines'), ('approve_grant_line_budget', 'Can approve grant line budgets')], 'verbose_name': 'Grant Line'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['item_name'], 'permissions': [('manage_items', 'Can manage items'), ('view_item_reports', 'Can view item reports')], 'verbose_name': 'Item'},
        ),
        migrations.AlterModelOptions(
            name='line',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['line_name'], 'permissions': [('manage_lines', 'Can manage lines'), ('approve_line_budget', 'Can approve line budgets'), ('view_line_reports', 'Can view line reports')], 'verbose_name': 'Line'},
        ),
        migrations.AlterModelOptions(
            name='payperiod',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['periodStart'], 'permissions': [('manage_pay_periods', 'Can manage pay periods')], 'verbose_name': 'Pay Period'},
        ),
        migrations.AlterModelOptions(
            name='payroll',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['beg_date'], 'permissions': [('process_payroll', 'Can process payroll'), ('approve_payroll', 'Can approve payroll'), ('view_payroll_reports', 'Can view payroll reports')], 'verbose_name': 'Payroll'},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['name'], 'permissions': [('manage_people', 'Can manage people'), ('view_vendor_customer_reports', 'Can view vendor/customer reports')], 'verbose_name': 'People'},
        ),
        migrations.AlterModelOptions(
            name='testing',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['testing_name'], 'permissions': [('manage_testing', 'Can manage testing')]},
        ),
    ]
