# Generated by Django 5.1.6 on 2026-05-19 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0129_alter_activitylist_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='employee',
        ),
    ]
