# Generated by Django 5.1.6 on 2026-05-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0130_remove_revenue_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='line_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Line ID'),
        ),
    ]
