# Generated by Django 5.1.6 on 2026-05-19 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0131_alter_line_line_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='grantLine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WCHDApp.grantline', verbose_name='Grant Line'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='payType',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Check', 'Check'), ('Electronic Transfer', 'Electronictransfer'), ('Online Payment', 'Onlinepayment')], max_length=20, verbose_name='Payment Type'),
        ),
    ]
