# Generated by Django 5.1.6 on 2026-05-20 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0133_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='WCHDApp.employee', verbose_name='Employee'),
        ),
    ]
