# Generated by Django 5.1.6 on 2026-05-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0134_revenue_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='payType',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Check', 'Check'), ('Electronic Transfer', 'Electronic Transfer'), ('Online Payment', 'Online Payment')], max_length=20, verbose_name='Payment Type'),
        ),
    ]
