# Generated by Django 5.1.6 on 2026-05-20 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0135_alter_revenue_paytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
