# Generated by Django 5.1.6 on 2026-05-21 15:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0136_alter_revenue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='clockify_project',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Clockify Project'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='paycode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Paycode'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='ActivityList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WCHDApp.activitylist', verbose_name='Activity List'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
