# Generated by Django 5.1.6 on 2026-05-21 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0137_payroll_clockify_project_payroll_paycode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='ActivityList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WCHDApp.activitylist', verbose_name='Activity List'),
        ),
    ]
