# Generated by Django 5.1.6 on 2026-05-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0138_alter_expense_activitylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='clockify_department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Clockify Department'),
        ),
    ]
