# Generated by Django 5.1.6 on 2026-02-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0144_alter_employee_city_alter_employee_dob_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variable',
            new_name='InsuranceRate',
        ),
        migrations.AlterModelOptions(
            name='activitylist',
            options={'ordering': ['ActivityList_id']},
        ),
        migrations.AlterModelOptions(
            name='benefits',
            options={'ordering': ['employee']},
        ),
        migrations.AlterModelOptions(
            name='budgetactions',
            options={'ordering': ['ba_id']},
        ),
        migrations.AlterModelOptions(
            name='carryover',
            options={'ordering': ['dept']},
        ),
        migrations.AlterModelOptions(
            name='dept',
            options={'ordering': ['dept_name']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['surname', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='fund',
            options={'ordering': ['fund_name']},
        ),
        migrations.AlterModelOptions(
            name='grant',
            options={'ordering': ['grant_name']},
        ),
        migrations.AlterModelOptions(
            name='grantitem',
            options={'ordering': ['item_name']},
        ),
        migrations.AlterModelOptions(
            name='grantline',
            options={'ordering': ['grant']},
        ),
        migrations.AlterModelOptions(
            name='insurancerate',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['item_name']},
        ),
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ['line_name']},
        ),
        migrations.AlterModelOptions(
            name='payperiod',
            options={'ordering': ['periodStart']},
        ),
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['beg_date']},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='revenue',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='testing',
            options={'ordering': ['testing_name']},
        ),
        migrations.AlterField(
            model_name='fund',
            name='fund_total',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Revenue'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='reference',
            field=models.CharField(max_length=50, verbose_name='Reference'),
        ),
        migrations.AlterModelTable(
            name='insurancerate',
            table='Insurance Rate',
        ),
    ]
