# Generated by Django 5.1.6 on 2026-02-28 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0145_rename_variable_insurancerate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GrantItem',
        ),
    ]
