# Generated by Django 5.1.6 on 2026-04-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0146_delete_grantitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesscontrol',
            options={'permissions': [('has_full_access', 'Has full access to all views')], 'verbose_name': 'Access Control'},
        ),
        migrations.AlterModelOptions(
            name='activitylist',
            options={'ordering': ['ActivityList_id'], 'verbose_name': 'Activity List'},
        ),
        migrations.AlterModelOptions(
            name='benefits',
            options={'ordering': ['employee'], 'verbose_name': 'Benefits'},
        ),
        migrations.AlterModelOptions(
            name='budgetactions',
            options={'ordering': ['ba_id'], 'verbose_name': 'Budget Actions'},
        ),
        migrations.AlterModelOptions(
            name='carryover',
            options={'ordering': ['dept'], 'verbose_name': 'Carryover'},
        ),
        migrations.AlterModelOptions(
            name='dept',
            options={'ordering': ['dept_name'], 'verbose_name': 'Dept'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['surname', 'first_name'], 'verbose_name': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['date'], 'verbose_name': 'Expense'},
        ),
        migrations.AlterModelOptions(
            name='fund',
            options={'ordering': ['fund_id', 'fund_name'], 'verbose_name': 'Fund'},
        ),
        migrations.AlterModelOptions(
            name='grant',
            options={'ordering': ['grant_name'], 'verbose_name': 'Grant'},
        ),
        migrations.AlterModelOptions(
            name='grantline',
            options={'ordering': ['grant'], 'verbose_name': 'Grant Line'},
        ),
        migrations.AlterModelOptions(
            name='insurancerate',
            options={'ordering': ['name'], 'verbose_name': 'Insurance Rate'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['item_name'], 'verbose_name': 'Item'},
        ),
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ['line_name'], 'verbose_name': 'Line'},
        ),
        migrations.AlterModelOptions(
            name='payperiod',
            options={'ordering': ['periodStart'], 'verbose_name': 'Pay Period'},
        ),
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['beg_date'], 'verbose_name': 'Payroll'},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['name'], 'verbose_name': 'People'},
        ),
        migrations.AlterModelOptions(
            name='revenue',
            options={'ordering': ['date'], 'verbose_name': 'Revenue'},
        ),
        migrations.AlterField(
            model_name='insurancerate',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='insurancerate',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterModelTable(
            name='accesscontrol',
            table='Access Control',
        ),
    ]
