# Generated by Django 5.1.6 on 2026-04-01 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0147_alter_accesscontrol_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurancerate',
            options={'ordering': ['year', 'month', 'person']},
        ),
        migrations.RemoveField(
            model_name='insurancerate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='insurancerate',
            name='value',
        ),
        migrations.AddField(
            model_name='insurancerate',
            name='dental',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='insurancerate',
            name='health',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='insurancerate',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurancerate',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.people'),
        ),
        migrations.AddField(
            model_name='insurancerate',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='insurancerate',
            table=None,
        ),
    ]
