# Generated by Django 5.1.6 on 2026-04-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0148_alter_insurancerate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurancerate',
            options={'ordering': ['year', 'month', 'person'], 'verbose_name': 'Insurance Rate', 'verbose_name_plural': 'Insurance Rates'},
        ),
        migrations.AlterField(
            model_name='insurancerate',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='insurancerate',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, default=2026, null=True),
        ),
        migrations.AlterModelTable(
            name='insurancerate',
            table='Insurance Rate',
        ),
    ]
