# Generated by Django 5.1.6 on 2026-04-02 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0147_alter_accesscontrol_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('percent_of_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.fund')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.people')),
            ],
            options={
                'verbose_name': 'Insurance Percentage',
                'verbose_name_plural': 'Insurance Percentages',
                'db_table': 'Insurance Percentage',
                'ordering': ['year', 'month', 'person', 'fund'],
            },
        ),
    ]
