# Generated by Django 5.1.6 on 2026-04-08 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0150_alter_insurancerate_month_alter_insurancerate_person_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurancepercentage',
            options={'ordering': ['start_date', 'end_date', 'person', 'fund'], 'verbose_name': 'Insurance Percentage', 'verbose_name_plural': 'Insurance Percentages'},
        ),
        migrations.RemoveField(
            model_name='insurancepercentage',
            name='month',
        ),
        migrations.RemoveField(
            model_name='insurancepercentage',
            name='year',
        ),
        migrations.AddField(
            model_name='insurancepercentage',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurancepercentage',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InsuranceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('health_type', models.CharField(blank=True, max_length=50)),
                ('health_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dental_type', models.CharField(blank=True, max_length=50)),
                ('dental_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('life_type', models.CharField(blank=True, max_length=50)),
                ('life_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.people')),
            ],
            options={
                'verbose_name': 'Insurance Assignment',
                'verbose_name_plural': 'Insurance Assignments',
                'db_table': 'Insurance Rate',
                'ordering': ['year', 'person'],
                'unique_together': {('person', 'year')},
            },
        ),
        migrations.DeleteModel(
            name='InsuranceRate',
        ),
    ]
