# Generated by Django 5.1.6 on 2026-04-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0150_alter_insurancerate_month_alter_insurancerate_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='people',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='people',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='people',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='people',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip Code'),
        ),
    ]
