# Generated by Django 5.1.6 on 2026-04-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0151_alter_insurancepercentage_options_and_more'),
        ('WCHDApp', '0151_alter_people_address_alter_people_city_and_more'),
    ]

    operations = [
    ]
